# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{vocab_counter}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Julian Burgess"]
  s.date = %q{2009-11-07}
  s.default_executable = %q{vocab_counter}
  s.description = %q{Produces a CSV sorted by the number of times each term appears (case insensitive, lowercase output).}
  s.email = %q{aubergene@gmail.com}
  s.executables = ["vocab_counter"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/vocab_counter",
     "lib/vocab_counter.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/vocab_counter_spec.rb",
     "vocab_counter.gemspec"
  ]
  s.homepage = %q{http://github.com/aubergene/vocab_counter}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Count the number of unique terms in a given text}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/vocab_counter_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

